#!/bin/bash
# Generates RUST_THIRD_PARTY_NOTICES.md from the crates resolved in Cargo.lock,
# using `cargo license` (https://github.com/onur/cargo-license) since Cargo.lock
# itself carries no license metadata.
set -e

if ! command -v cargo-license &> /dev/null; then
  echo "cargo-license is not installed."
  echo "Install it once with: cargo install cargo-license"
  echo "Then re-run this script."
  exit 1
fi

OUT="RUST_THIRD_PARTY_NOTICES.md"

{
  echo "# Rust Third-Party Notices"
  echo
  echo "Generated by \`scripts/generate-rust-license-notices.sh\` via \`cargo license\`."
  echo "Do not edit by hand — regenerate it instead. See"
  echo "[docs/LICENSING_AND_THIRD_PARTY_NOTICES.md](docs/LICENSING_AND_THIRD_PARTY_NOTICES.md)."
  echo
  echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo '```'
  cargo license --avoid-dev-deps
  echo '```'
} > "$OUT"

echo "Wrote $OUT"
